#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage: .codex/run-weekly-bug-hunt.sh [options]

Runs Codex non-interactively against the project's bug-hunt prompt and stores
run artifacts under local/bug-hunt-runs/<timestamp>/.

Options:
  --model <name>               Codex model to use
  --prompt <path>              Prompt file to use
  --runs-dir <path>            Artifact directory root
  --worktrees-dir <path>       Worktree directory root
  --branch-prefix <prefix>     Prefix for the autogenerated git branch
  --allow-dirty                Run even if the git worktree is dirty
  --no-worktree                Run in the current checkout instead
  --no-branch                  Reuse the current branch instead of creating one
  --dangerous                  Use Codex with approvals and sandbox bypassed
  --extra-instruction <text>   Append an extra instruction before the prompt
  --help                       Show this help

Examples:
  .codex/run-weekly-bug-hunt.sh
  .codex/run-weekly-bug-hunt.sh --model gpt-5.4
  .codex/run-weekly-bug-hunt.sh --dangerous --allow-dirty --no-worktree
EOF
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

prompt_path=".codex/bug-hunt-prompt.md"
runs_dir="local/bug-hunt-runs"
worktrees_dir=".worktrees"
branch_prefix="codex/weekly-bug-hunt"
model=""
allow_dirty=0
use_worktree=1
create_branch=1
dangerous=0
declare -a extra_instructions=()

while (($# > 0)); do
  case "$1" in
    --model)
      model="${2:?missing model value}"
      shift 2
      ;;
    --prompt)
      prompt_path="${2:?missing prompt path}"
      shift 2
      ;;
    --runs-dir)
      runs_dir="${2:?missing runs dir}"
      shift 2
      ;;
    --worktrees-dir)
      worktrees_dir="${2:?missing worktrees dir}"
      shift 2
      ;;
    --branch-prefix)
      branch_prefix="${2:?missing branch prefix}"
      shift 2
      ;;
    --allow-dirty)
      allow_dirty=1
      shift
      ;;
    --no-worktree)
      use_worktree=0
      shift
      ;;
    --no-branch)
      create_branch=0
      shift
      ;;
    --dangerous)
      dangerous=1
      shift
      ;;
    --extra-instruction)
      extra_instructions+=("${2:?missing instruction text}")
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

require_command codex
require_command git
require_command date
require_command mkdir
require_command tee

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

if [[ ! -f "$prompt_path" ]]; then
  echo "Prompt file not found: $prompt_path" >&2
  exit 1
fi

timestamp="$(date -u +%Y%m%dT%H%M%SZ)"
mkdir -p "$runs_dir"
run_dir="$runs_dir/$timestamp"
mkdir -p "$run_dir"

status_file="$run_dir/status.txt"
metadata_file="$run_dir/metadata.txt"
prompt_copy="$run_dir/prompt.md"
console_log="$run_dir/codex.log"
final_message_file="$run_dir/final-message.md"

current_branch="$(git branch --show-current || true)"
if [[ -z "$current_branch" ]]; then
  current_branch="detached-head"
fi

head_sha="$(git rev-parse --short HEAD)"
dirty=0
if [[ -n "$(git status --porcelain)" ]]; then
  dirty=1
fi

if (( dirty && !allow_dirty && !use_worktree )); then
  cat >&2 <<EOF
Refusing to run with a dirty git worktree.

Commit, stash, or discard your current changes first, or rerun with:
  .codex/run-weekly-bug-hunt.sh --allow-dirty
EOF
  exit 1
fi

if (( dirty && use_worktree && !allow_dirty )); then
  echo "Warning: root checkout is dirty; the worktree run will start from committed HEAD only." >&2
fi

if (( use_worktree && !create_branch )); then
  cat >&2 <<EOF
--no-branch is not supported together with the default worktree mode.

Use the default branch creation behavior, or disable worktree mode with:
  .codex/run-weekly-bug-hunt.sh --no-worktree --no-branch
EOF
  exit 1
fi

run_branch="$current_branch"
run_checkout="$repo_root"
worktree_path=""
if (( create_branch )); then
  safe_branch="${current_branch//\//-}"
  run_branch="${branch_prefix}/${safe_branch}-${timestamp}"
fi

if (( use_worktree )); then
  safe_worktree_name="${run_branch//\//-}"
  worktree_path="$repo_root/$worktrees_dir/$safe_worktree_name"
  mkdir -p "$repo_root/$worktrees_dir"

  if (( create_branch )); then
    git worktree add -b "$run_branch" "$worktree_path" >/dev/null
  else
    git worktree add "$worktree_path" "$run_branch" >/dev/null
  fi

  run_checkout="$worktree_path"
elif (( create_branch )); then
  git switch -c "$run_branch" >/dev/null
fi

{
  echo "status=running"
  echo "started_at_utc=$timestamp"
  echo "repo_root=$repo_root"
  echo "head_sha=$head_sha"
  echo "prompt_path=$prompt_path"
  echo "base_branch=$current_branch"
  echo "run_branch=$run_branch"
  echo "run_checkout=$run_checkout"
  echo "worktree_path=$worktree_path"
  echo "dirty_at_start=$dirty"
  echo "used_worktree=$use_worktree"
  echo "dangerous_mode=$dangerous"
  if [[ -n "$model" ]]; then
    echo "model=$model"
  fi
} >"$metadata_file"
echo "running" >"$status_file"

{
  cat <<EOF
You are running from the committed wrapper script at .codex/run-weekly-bug-hunt.sh.

Execution context:
- Repository root: $repo_root
- Execution checkout: $run_checkout
- Prompt source: $prompt_path
- Artifact directory for this run: $run_dir
- Current git branch for this run: $run_branch

Operating instructions for this automated run:
- Work fully autonomously inside this repository.
- Keep any temporary files or status artifacts under local/.
- Work only inside the current checkout at $run_checkout.
- Use the current git branch. Do not switch branches.
- Commit bug fixes when appropriate according to the prompt.
- End with a concise run report that lists bugs fixed, commands run, and any unfinished leads.
- Read and follow CLAUDE.md plus relevant files under .claude/ when they help you interpret local project conventions.

EOF

  for instruction in "${extra_instructions[@]}"; do
    printf -- "- Extra instruction: %s\n" "$instruction"
  done

  if ((${#extra_instructions[@]} > 0)); then
    printf "\n"
  fi

  cat "$prompt_path"
} >"$prompt_copy"

declare -a codex_args
codex_args=(exec --cd "$run_checkout" --color never -o "$final_message_file")

if [[ -n "$model" ]]; then
  codex_args+=(--model "$model")
fi

if (( dangerous )); then
  codex_args+=(--dangerously-bypass-approvals-and-sandbox)
else
  codex_args+=(--full-auto)
fi

echo "Launching Codex in $run_checkout on branch $run_branch"
echo "Artifacts will be written to $run_dir"

set +e
codex "${codex_args[@]}" - <"$prompt_copy" 2>&1 | tee "$console_log"
codex_exit="${PIPESTATUS[0]}"
set -e

finished_at="$(date -u +%Y%m%dT%H%M%SZ)"
{
  echo "finished_at_utc=$finished_at"
  echo "codex_exit=$codex_exit"
  echo "git_status_after_run<<EOF"
  git -C "$run_checkout" status --short
  echo "EOF"
} >>"$metadata_file"

if [[ "$codex_exit" -eq 0 ]]; then
  echo "success" >"$status_file"
echo "Run completed successfully."
else
  echo "failed" >"$status_file"
  echo "Run failed with exit code $codex_exit" >&2
fi

if [[ -n "$worktree_path" ]]; then
  echo "Worktree: $worktree_path"
fi
echo "Branch: $run_branch"
echo "Status file: $status_file"
echo "Metadata: $metadata_file"
echo "Prompt copy: $prompt_copy"
echo "Console log: $console_log"
echo "Final message: $final_message_file"

exit "$codex_exit"
